### ISSUE TITLE
Dead link: https://rsinger86.github.io/usage/view_set_usage

### ISSUE THREAD

**Issue by hollerith** [rsinger86/drf-access-policy#17]
On the page https://rsinger86.github.io/drf-access-policy/ the 'Read On' link on the bottom of that page href is: 

https://rsinger86.github.io/usage/view_set_usage

whereas it ought to be:

https://rsinger86.github.io/drf-access-policy/usage/view_set_usage/

**Comment by rsinger86** [comment]
thanks for catching this!
