### ISSUE TITLE
URL path variable in custom condition

### ISSUE THREAD

**Issue by tobiasge** [rsinger86/drf-access-policy#19]
This is more a question than an issue.
I have the following custom action on my `ModelViewSet`:
```python
@action(methods=["post", "delete"], detail=True, url_path="assign/(?P<userid>[^/.]+)")
def assign(self, request, pk=None, userid=None):
```
And on the `AccessPolicy` I have a method:
```python
def self_or_manager(self, request, view, action) -> bool:
```

I want to access the `userid` in my condition method. Is this possible?

Thanks,
Tobias

**Comment by rsinger86** [comment]
There might be multiple ways for you to do this. Your `self_or_manager` method is passed both the `view` instance and the `request` object:
- you can access `view.kwargs`dict  which will contain `userid`
- you can inspect the `request` object and parse the URL path

The first option is probably simpler.

**Comment by tobiasge** [comment]
Thanks, `view.kwargs` is what I was looking for.

And thanks for developing this. It is really helpful.
