### ISSUE TITLE
get_user_group_values is not efficient

### ISSUE THREAD

**Issue by filwaline** [rsinger86/drf-access-policy#24]
https://github.com/rsinger86/drf-access-policy/blob/ac3f70b0175222d57cbab3cd7ed5b6b3da327ce9/rest_access_policy/access_policy.py#L26
```
    def get_user_group_values(self, user) -> List[str]:
        return list(user.groups.values_list("name", flat=True))
```

AccessPolicy heavily rely on compute current user's groups, but this implementation seems bad... It will hit database every time(reported by [django-debug-toolbar](https://django-debug-toolbar.readthedocs.io/en/latest/index.html)), rather than using cache. For example, `User.objects.prefetch_related('groups').all()` take no credits here.

Simply change a bit will make a big progress:
```
# prefetch related somewhere
# user = User.objects.prefetch_related('groups').get(...)
...
    def get_user_group_values(self, user) -> List[str]:
        return [g.name for g in user.groups.all()]
```
From now on, no matter how many calls of `get_user_group_values`, database only get two queries(prefetch take one extra query). If `User` model haven't prefetch with `Group`, things still keep the same, it won't get worse. 

And there is a better solution, using [cache_property](https://docs.djangoproject.com/en/3.0/topics/performance/#cached-property), but this need to define a method in model, which can't not handled by assess policy.

**Comment by KillianMeersman** [comment]
https://github.com/rsinger86/drf-access-policy/blob/ac3f70b0175222d57cbab3cd7ed5b6b3da327ce9/rest_access_policy/access_policy.py#L81

`user_roles` is also fetched unnecessarily, it's only used in the else clause of the principal loop.
If there are no user groups in any principals this is a wasted database query.

A possible solution is to set the `user_groups` to `None` at first, and initialize it in the else-clause if need be. This way lookups will only happen if necessary and not more than once.

**Comment by filwaline** [comment]
BTW, [prefetch_related_objects](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#prefetch-related-objects) is work perfectly with list comprehension here.
```
    def get_user_group_values(self, user) -> List[str]:
        prefetch_related_objects([user], 'groups')
        return [g.name for g in user.groups.all()]
```
If `User` model haven't prefetch with `Group`, then prefetch_related_objects will finish the jobs, attach query result as a cache of `user` instance(hit database one time).

If `user` instance already has cache of `groups`, then prefetch_related_objects will just pass, no more extra database query.

**Comment by rsinger86** [comment]
Thanks for the pull requests. These are merged in now. @filwaline - regarding use of cache_property decorator on User model, you may consider subclassing `AccessPolicy` and with your own custom `get_user_group_values` method.
