### ISSUE TITLE
Response philosophy based on type of failure

### ISSUE THREAD

**Issue by lorinkoz** [rsinger86/drf-access-policy#31]
Pardon me if I got a bit excited about this package. This issue is basically a philosophical discussion that goes outside the scope of this project.

I know that DRF's custom permissions are rather limited in that you can only return a boolean and DRF will take care of the response. Thinking in how you're combining static checks with more dynamic checks, it would be great if the error response could be made more explicit depending on the type of failure. Let me explain myself.

I consider a static check to be something that is unlikely to change over time. User or role based permissions are a good example of those, as permissions attached to users/roles do not depend on the state of the system. A dynamic check would be something that depends on the state of the system, that is, something that would fit in a "condition" of the statement.

To me, it's not philosophically correct to treat a failure on each situation in the same way, that is, it's not fair to just give a plain 403 on each and all situations. If a user doesn't have permission to perform certain action based on the user itself or its roles, that's a typical 403. However, if the failure comes from a condition that tested positive in the current request, but is likely to test negative when the system changes (e.g. `is_happy_hour`), then, a different type of error would be expected, in order to tell the user that the 403 is not permanent. If not a different response status, at least a different level of details in the error response body.

Are you making such distinctions in your own uses of this package? Do you know of any DRF hook that would make something like this possible, other than possibly annotating the request and capturing the exception on the way out via middleware?

**Comment by rsinger86** [comment]
I have not yet had to make that distinction, but I see your point. I think this could be accomplished with DRF's custom exception handling and a custom exception class: 
https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling

In the condition check that fails in the access policy, the custom exception could be raised and the custom exception handler could examine the type of exception raised and alter the response accordingly. DRF permissions are intended to return booleans, not raise exceptions, so maybe this isn't ideal.

**Comment by alikins** [comment]
@lorinkoz https://github.com/rsinger86/drf-access-policy/issues/45 is similar. I added some notes about an approach I am experimenting with that could possible be useful: https://github.com/rsinger86/drf-access-policy/issues/45#issuecomment-791550298
