### ISSUE TITLE
Can i use it on generic api views ?

### ISSUE THREAD

**Issue by mmohajer9** [rsinger86/drf-access-policy#37]
hi , my question is simple , can i use it on generic api views ? like list api view or create api view ?

**Comment by rsinger86** [comment]
Yes, it's compatible but keep in mind that the `action` will be equal to the name of the view class since generic views don't set this property.

So if this is your class:
```python
class UserList(ListAPIView):
    permission_classes = (UserAccessPolicy,)
    serializer_class = UserAccountSerializer
    queryset = UserAccount.objects.all()
```

So the `action` here would be `"UserList"` which ... doesn't really sound like an action.

**Comment by mmohajer9** [comment]
> Yes, it's compatible but keep in mind that the `action` will be equal to the name of the view class since generic views don't set this property.
> 
> So if this is your class:
> 
> ```python
> class UserList(ListAPIView):
>     permission_classes = (UserAccessPolicy,)
>     serializer_class = UserAccountSerializer
>     queryset = UserAccount.objects.all()
> ```
> 
> So the `action` here would be `"UserList"` which ... doesn't really sound like an action.

**Aha, got it ! Thank you !**
