### ISSUE TITLE
scope_queryset not working

### ISSUE THREAD

**Issue by hardntrash** [rsinger86/drf-access-policy#43]
I have ModelViewSet with permission_class and override method scope_querset inside, but it isn't called  (if not override, parent's method not called too). what could be?

**Comment by rsinger86** [comment]
Could you post the relevant parts of your code here?

**Comment by hardntrash** [comment]
![изображение](https://user-images.githubusercontent.com/16561437/100576544-2f35be80-3300-11eb-9c5e-721941f44d14.png)

Method scope_querset is unused and isn't called anywhere. How to use it? Maybe i should in ViewSet to assign queryset value from this method? Or, if possible, advise the correct use

**Comment by rsinger86** [comment]
Hi -- sorry about the delay in responding. 

Here's an example below. It's a way to virtually segregate the database. For example, in a multi-tenant app, users of one tenant should have no awareness of another tenant's objects/rows. By having the `scope_queryset` method on the access policy class, the idea is to centralize the access logic. 

ViewSet:
```python    
@property
    def access_policy(self):
        return self.permission_classes[0]

    def get_queryset(self):
        qs = self.access_policy.scope_queryset(self.request, Task.objects.all())
```

AccessPolicy:

```python
    @classmethod
    def scope_queryset(cls, request, qs):
        return qs.filter(tenant_id=request.user.tenant_id, soft_delete=False)
```

**Comment by hardntrash** [comment]
ty, i will try. I think this isn't native solution and requires a description of this example in documentation. If possible, i will do it

**Comment by puraminy** [comment]
what is `self.request` for ViewSets in the following code you posted? Do they have such property or it should be defined and assigned?

```

    def get_queryset(self):
        qs = self.access_policy.scope_queryset(self.request, Task.objects.all())
```

I get:

```
File "/home/ahmad/jkar/karmodir/views.py", line 47, in get_queryset
    self.request, self.queryset)
AttributeError: 'MemberViewSet' object has no attribute 'request'

```
