### ISSUE TITLE
Version 0.8.5 breaks conditions with `*` as params

### ISSUE THREAD

**Issue by igorjacauna** [rsinger86/drf-access-policy#49]
I use my conditions with this behaviour when I want to allow any action based in some logics requireds in my application:

```python
class MyPolicy(AccessPolicy):

    statements = [
        {
            'action': '*',
            'principal': 'authenticated',
            'effect': 'allow',
            'condition': ['check_permissions:*']  # this could be `check_permissions:can_add,can_read,can_this,can_that` but to prevent write all, I use *
        }
    ]

    def check_permissions(self, request, view, action, permissions)
        if permissions == '*':
             return True
        else:
             # Checking others conditions based on permissions param like 'can_add,can_read'
```

`check_permissions:*`, this is a condition to allow any action based on values in Database and others logics.

But with 0.8.5 its breaks my implementation because it is passing `None` to `permissions` param in `check_permissions`

I was forced to downgrade to 0.8.1 to make my app works again and I we can't refactoring entire application because of the time and cost we will have.

So I'm justin reporting the issue that we faced with this version

**Comment by rsinger86** [comment]
thanks for reporting. this is fixed in latest release.
