### ISSUE TITLE
Introduction of support for condition expressions is a breaking change on existing condition strings

### ISSUE THREAD

**Issue by ajcsimons** [rsinger86/drf-access-policy#55]
First of all, thanks for a nice project, it's neat to be able to dynamically load json of access policy statements to apply highly configurable permissions with custom condition functions. We use this in a real-world application with real customers with real security implications.

We recently upgraded to 0.8.7 and discovered that a load of permission rules were now being ignored (so people who aren't supposed to be allowed to do things can now do them). Reason is this change: https://github.com/rsinger86/drf-access-policy/commit/199d53ac396dbafb47c14a85a8ec71fdb1a974d1# It's trying to be clever and parsing the condition string, which means the wrong value is passed to a condition function. For example we had this condition string working fine in 0.7.0

`"can_edit_event_attribute:start_date,end_date:EDIT_EVENT_DATES"`

can_edit_event_attribute is a custom function on the access policy which takes the string argument _start_date,end_date:EDIT_EVENT_DATES_ splits by colon to get attributes list which is comma separated, and then permission name. So logically this is saying "If you want to change the start_date or end_date fields in a json payload to this endpoint, you need the permission object EDIT_EVENT_DATES. This worked very nicely because when customers said "Hey, I also want to restrict the _duration_ field with that same permission", we could just update the string in policy json to _start_date,end_date,duration:EDIT_EVENT_DATES_ and bingo it works with config not code change. We have adopted this pattern of condition strings being a colon separated bunch of clauses which can themselves be comma separated as a way of passing arguments into the custom condition functions and it's powerful and convenient.

But now that the condition string is being parsed, the comma is making that string get truncated and all that is passed to the can_edit_event_attribute condition function is incorrectly 'start_date' rather than 'start_date,end_date:EDIT_EVENT_DATES'.

I appreciate being able to do logical expressions in the condition strings is useful, but it is not backwards compatible and could be breaking lots of other clients too (who might not notice that users can now subvert the permission rules).

I see the most recent change added '*' character to what counts as a word for the tokenizer. So the easy fix here would be adding comma too and that would fix my use case. But other clients could have condition strings containing spaces or the string OR if they'd built their own parser of condition strings so that's not really a good general fix. The crux of the issue is that it's invalid to apply a parser/tokenizer to what used to be a simple string and clients were relying on receiving verbatim. Maybe the solution is to introduce a new property in the json 'condition_expression' that supports the parsing, and 'condition' does no parsing and passes the string verbatim to avoid breaking clients relying on that prior behaviour.

**Comment by rsinger86** [comment]
I totally see your point. Yes, I think a separate `condition_expression` is the way to go. Any recommendations on how to best inform users about this change?

**Comment by rsinger86** [comment]
Thanks for raising this. Added a separate `condition_expression` in 1.0 update:
https://rsinger86.github.io/drf-access-policy/migration_notes.html
