### ISSUE TITLE
How to implement field based access as mentioned in the docs?

### ISSUE THREAD

**Issue by normic** [rsinger86/drf-access-policy#87]
Great package 🥇 Much clearer adn more flexible than the DRF build in permission system.

I appreciate the feature [Field Level Permissions](https://rsinger86.github.io/drf-access-policy/field_level_permissions/) but can't get it to work fully.

From the docs: 
_Often, depending on the user, not all fields should be visible or only a subset should be writable._

The docs example shows how to remove a field at all, but I can't figure out how to achieve making one or more fields read_only. Even lurking at the source does not help me figure it out.

Would it be possible to explain that a little more or giving a hint how to achieve "only a subset should be writable"?

Thanks.

**Comment by rsinger86** [comment]
Sure! I added some more details here:
https://rsinger86.github.io/drf-access-policy/field_level_permissions.html
